/*
 *
 * Automatically generated file; DO NOT EDIT.
 * ASR3601 Open Configuration
 *
 */
#define CONFIG_QUECTEL_PROJECT_REV "EC100YCNAAR01A03M16_OCPU_BETA0429"
#define CONFIG_QUECTEL_PROJECT_NAME "EC100YCNAA"
#define CONFIG_QUECTEL_PROJECT_EC100YCN_AA 1
